# Generated by Django 2.2 on 2020-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabily',
            field=models.TextField(choices=[('In Stock', 'In Stock'), ('Out Of Range', 'Out Of Range')], max_length=15),
        ),
    ]
