# Generated by Django 2.2 on 2020-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200719_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('slider_img', models.ImageField(upload_to='Images')),
                ('text1', models.CharField(max_length=90)),
                ('text2', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='availabily',
            field=models.TextField(choices=[('In Stock', 'In Stock'), ('Out Of Range', 'Out Of Range'), ('Limited Stock', 'Limited Stock')], max_length=15),
        ),
    ]
