# Generated by Django 2.2 on 2020-07-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_ids',
            new_name='product_ids',
        ),
    ]
